// This file is autogenerated by liwe3-svelte
/* eslint-disable @typescript-eslint/no-explicit-any */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

/** Media */
export interface Media {
	/** the main id field */
	id: string;
	/**  */
	domain?: string;
	/** The user id that uploaded this media */
	id_owner?: string;
	/** The folder containing this media */
	id_folder?: string;
	/** Media title */
	title?: string;
	/** Upload file name */
	name?: string;
	/** The original uploaded file name  */
	original_filename?: string;
	/** The file mimetype  */
	mimetype?: string;
	/** The path of the generated thumbnail */
	thumbnail?: string;
	/** The uploaded path */
	path?: string;
	/** The uploaded filename  */
	filename?: string;
	/** The absolute path and filename  */
	abs_path?: string;
	/** File size in bytes */
	size?: number;
	/** File Extension  */
	ext?: string;
	/** Flag T/F that tells if the media is ready */
	is_ready?: boolean;
	/** MD5 file checksum */
	md5?: string;
	/** tags for this media */
	tags?: string[];
	/** Latitude */
	lat?: string;
	/** Longitude */
	lng?: string;
	/** Width in pixels */
	width?: number;
	/** Height in pixels */
	height?: number;
	/** Year of creation of the media */
	year?: number;
	/** Month of creation of the media */
	month?: number;
	/** Date of creation of the media */
	creation?: Date;
	/** If a photo is vertical or horizontal */
	orientation?: number;
	/** Image EXIF metadata */
	exif?: any;
}

/** MediaBind */
export interface MediaBind {
	/** the main id field */
	id: string;
	/**  */
	id_media: string;
	/**  */
	id_object: string;
	/**  */
	module: string;
}

/** MediaFolder */
export interface MediaFolder {
	/** the main id field */
	id: string;
	/** The domain */
	domain?: string;
	/** The parent folder */
	id_parent?: string;
	/**  */
	name: string;
	/** IDs of Media Folders */
	subfolders?: string[];
	/** IDs of Medias in this folder */
	medias?: string[];
}

/** MediaTreeItem */
export interface MediaTreeItem {
	/** the main id field */
	id: string;
	/**  */
	id_parent?: string;
	/**  */
	name: string;
	/**  */
	subfolders: MediaTreeItem[];
}

